export default {
  eventTypes: {},
  events: {},
  crops: [],
  items: {},
  categories: {},
  subCategories: {},
  recipes: {},
  mounts: {
    mounts: {},
    types: {},
    obtainTypes: {},
  },
  classes: [],
  skillsets: {},
  skills: {},
  vocationRecipes: {},
  vocations: [],
  quests: {},
  questCategories: {},
  questCriteriaTypes: {},
  dailyQuests: [],
  rewardTypes: {},
  instances: {},
  festivals: {},
  titles: {},
  npcs: {},
  doodads: {},
};
