export const DATA_CATEGORIES = 'DATA_CATEGORIES';
export const DATA_ITEM = 'DATA_ITEM';
export const DATA_RECIPE = 'DATA_RECIPE';
export const DATA_VOCATION_RECIPE = 'DATA_VOCATION_RECIPE';
export const DATA_VOCATION = 'DATA_VOCATION';
