export const MY_CHARACTERS_ADD = 'MY_CHARACTERS_ADD';
export const MY_CHARACTERS_DELETE = 'MY_CHARACTERS_DELETE';
export const MY_CHARACTERS_RENAME = 'MY_CHARACTERS_RENAME';

export const MAX_CHARACTERS = 6;
