import * as Icon from '../images/buff/';
import * as ArcheryIcon from '../images/skill/archery/';
import * as AuramancyIcon from '../images/skill/auramancy/';
import * as BattlerageIcon from '../images/skill/battlerage/';
import * as DefenseIcon from '../images/skill/defense/';
import * as MaledictionIcon from '../images/skill/malediction/';
import * as OccultismIcon from '../images/skill/occultism/';
import * as ShadowplayIcon from '../images/skill/shadowplay/';
import * as SongcraftIcon from '../images/skill/songcraft/';
import * as SorceryIcon from '../images/skill/sorcery/';
import * as VitalismIcon from '../images/skill/vitalism/';
import * as WitchcraftIcon from '../images/skill/witchcraft/';

export const MAX_POINTS = 18;

export const DEFAULT_SKILLS = new Array(12).fill(0);
export const DEFAULT_ANCESTRALS = new Array(6).fill(0);
export const ANCESTRAL_MAX = 4;
export const ANCESTRAL_LENGTH = 7;

export const ATTACK = Object.freeze({
  MELEE: 'Melee Attack',
  MAGIC: 'Magic Attack',
  RANGED: 'Ranged Attack',
  HEALING: 'Healing Power',
});

export const BUFF = Object.freeze({
  LIGHT_BLINDED: { name: 'Light Blinded', icon: ArcheryIcon.BlazingArrow, negative: true },
  BLEEDING: { name: 'Bleeding', icon: Icon.Bleeding, negative: true },
  BLESSED: { name: 'Blessed', icon: Icon.Blessed },
  BLINDED_BY_CROWS: { name: 'Blinded by Crows', icon: Icon.BlindedByCrows, negative: true },
  BLOODTHIRST_EXPLOSION: { name: 'Bloodthirst Explosion', icon: Icon.BloodthirstExplosion },
  BURNING: { name: 'Burning', icon: Icon.Burning, negative: true },
  CHARMED: { name: 'Charmed', icon: Icon.Charmed, negative: true },
  CONFINED: { name: 'Confined', icon: Icon.Confined, negative: true },
  CONFLAGRATION: { name: 'Conflagration', icon: Icon.Conflagration, negative: true },
  CURSED: { name: 'Cursed', icon: Icon.Cursed, negative: true },
  CURSED_SEEDS: { name: 'Cursed Seeds', icon: OccultismIcon.CursedThorns, negative: true },
  DEATHMARK_AURA: { name: 'Deathmark Aura', icon: Icon.DeathmarkAura, negative: true },
  DEEPFREEZE: { name: 'Deep Freeze', icon: Icon.Deepfreeze, negative: true },
  DISCORD: { name: 'Discord', icon: Icon.Discord, negative: true },
  DISSONANCE: { name: 'Dissonance', icon: SongcraftIcon.Dissonance, negative: true },
  DISTRESSED: { name: 'Distressed', icon: Icon.Distressed, negative: true },
  DIVINE_RESPONSE: { name: 'Divine Response', icon: Icon.DivineResponse },
  ELECTROCUTED: { name: 'Electrocuted', icon: Icon.Electrocuted, negative: true },
  ENERVATED: { name: 'Enervated', icon: WitchcraftIcon.Enervate, negative: true },
  EARTHEN_GRIP_DISARM: { name: 'Earthen Grip: Disarm', icon: WitchcraftIcon.EarthenGrip, negative: true },
  FEARED: { name: 'Feared', icon: Icon.Feared, negative: true },
  FREEZING: { name: 'Freezing', icon: Icon.Freezing, negative: true },
  FROZEN: { name: 'Frozen', icon: Icon.Frozen, negative: true },
  IMPALED: { name: 'Impaled', icon: Icon.Impaled, negative: true },
  INSTINCT: { name: 'Instinct', icon: Icon.Instinct, negative: true },
  LASSITUDE: { name: 'Lassitude', icon: WitchcraftIcon.Lassitude, negative: true },
  LAUNCHED: { name: 'Launched', icon: Icon.Launched, negative: true },
  MALICE_CHARGE: { name: 'Malice Charge', icon: Icon.MaliceCharge },
  MALICIOUS_BINDING: { name: 'Malicious Binding', icon: MaledictionIcon.MaliciousBinding, negative: true },
  OVER_HEALING: { name: 'Over Healing', icon: Icon.OverHealing, negative: true },
  OVERPOWERED: { name: 'Overpowered', icon: Icon.Overpowered, negative: true },
  PETRIFIED: { name: 'Petrified', icon: Icon.Petrified, negative: true },
  POISONED: { name: 'Poisoned', icon: Icon.Poisoned, negative: true },
  PRAYER: { name: 'Prayer', icon: Icon.Prayer },
  PROVOKE: { name: 'Provoked', icon: Icon.Provoke, negative: true },
  PURGE: { name: 'Purge', icon: WitchcraftIcon.Purge },
  RESURGENCE: { name: 'Resurgence', icon: Icon.Resurgence },
  SHACKLE: { name: 'Shackle', icon: Icon.Shackle, negative: true },
  SHAKEN: { name: 'Shaken', icon: Icon.Shaken, negative: true },
  MAGIC_SHIELD: { name: 'Magic Shield', icon: Icon.MagicShield },
  SILENCED: { name: 'Silenced', icon: Icon.Silenced, negative: true },
  SLEEPING: { name: 'Sleeping', icon: Icon.Sleeping, negative: true },
  SLOWED: { name: 'Slowed', icon: Icon.Slowed, negative: true },
  SNARED: { name: 'Snared', icon: Icon.Snared, negative: true },
  SNIPE_IMMUNITY: { name: 'Sniped', icon: Icon.SnipeImmunity, negative: true },
  STAGGER: { name: 'Stagger', icon: Icon.Stagger, negative: true },
  STUNNED: { name: 'Stunned', icon: Icon.Stunned, negative: true },
  SUMMON_CROWS: { name: 'Summon Crows', icon: OccultismIcon.SummonCrows, negative: true },
  TRIPPED: { name: 'Tripped', icon: Icon.Tripped, negative: true },
  VULNERABLE: { name: 'Vulnerable', icon: Icon.Vulnerable, negative: true },
  WEAKNESS: { name: 'Weakness', icon: Icon.Weakness, negative: true },

  FLIGHT_DISABLED: { name: 'Flight Disabled', icon: Icon.FlightDisabled, negative: true },
  POTIONS_DISABLED: { name: 'Potions Disabled', icon: Icon.PotionDisabled, negative: true },

  // buffs from skills
  TOUGHEN: { name: 'Toughen', icon: DefenseIcon.Toughen },
  DROP_BACK: { name: 'Drop Back', icon: ShadowplayIcon.DropBack },
  FRIGID_TRACKS: { name: 'Frigid Tracks', icon: SorceryIcon.FrigidTracks },
  INSULATING_LENS: { name: 'Insulating Lens', icon: SorceryIcon.InsulatingLens },
  BLOODTHIRST: { name: 'Bloodthirst', icon: ShadowplayIcon.BloodthirstIntensified },
  MARKED: { name: 'Marked', icon: ShadowplayIcon.StalkersMark, negative: true },
  STEALTHED: { name: 'Stealthed', icon: ShadowplayIcon.Stealth },
  STEALTHED_DEBUFF: { name: 'Stealthed', icon: ShadowplayIcon.Stealth, negative: true },
  CONVERSION_SHIELD: { name: 'Conversion Shield', icon: AuramancyIcon.ConversionShield },
  CONVERSION_SHIELD_FLAME: { name: 'Conversion Shield', icon: AuramancyIcon.ConversionShieldFlame },
  COURAGEOUS_ACTION: { name: 'Courageous Action', icon: AuramancyIcon.CourageousAction },
  FREERUNNER: { name: 'FreeRunner', icon: ShadowplayIcon.Freerunner },
  RENEWAL: { name: 'Renewal', icon: VitalismIcon.Renewal },
  PAIN_HARVEST: { name: 'Pain Harvest', icon: OccultismIcon.PainHarvest },
  DEATHS_VENGEANCE: { name: 'Death\'s Vengeance', icon: OccultismIcon.DeathsVengeance },
  HEALING_CIRCLE: { name: 'Healing Circle', icon: VitalismIcon.HealingCircle },
  WARDING_LIGHT: { name: 'Warding Light', icon: Icon.WardingLight },
  SHRUG_IT_OFF: { name: 'Shrug It Off', icon: AuramancyIcon.ShrugItOff },
  BATTLE_FOCUS: { name: 'Battle Focus', icon: BattlerageIcon.BattleFocus },
  FRENZY: { name: 'Frenzy', icon: BattlerageIcon.Frenzy },
  BULL_RUSH_AGGRO: { name: 'Bull Rush: Aggro Boost', icon: DefenseIcon.MockingHowl },
  RETRIBUTION: { name: 'Retribution', icon: DefenseIcon.Retribution },
  REDOUBT: { name: 'Redoubt', icon: DefenseIcon.Redoubt },
  REDOUBT_LIFE: { name: 'Redoubt', icon: DefenseIcon.RedoubtLife },
  STARTLING_STRAIN_LIFE: { name: 'Startling Strain: Life', icon: SongcraftIcon.StartlingStrainLife },
  FURY: { name: 'Fury', icon: MaledictionIcon.Fury },
  VOID_SURGE: { name: 'Void Surge', icon: MaledictionIcon.VoidSurge },
  SNOWLIONS: { name: 'Snowlions', icon: MaledictionIcon.GhastlyPack },
  STEADY_SHOOTING: { name: 'Steady Shooting', icon: ArcheryIcon.SteadyShooting },
  DEADEYE: { name: 'Deadeye', icon: ArcheryIcon.Deadeye },
});

Object.values(BUFF).forEach(b => !b.icon && console.warn('Buff Missing Icon:', b.name));

export const GLOBAL_CD = Object.freeze({
  NONE: 0,
  NO_TRIGGER: 1,
  REDUCED: 2,
  REDUCED_USEWHILE: 3,
  INCREASED: 4,
  NORMAL: 5,
});

export const ELEMENT = Object.freeze({
  BASIC: 'Basic',
  FLAME: 'Flame',
  LIGHTNING: 'Lightning',
  GALE: 'Gale',
  MIST: 'Mist',
  WAVE: 'Wave',
  STONE: 'Stone',
  QUAKE: 'Quake',
  LIFE: 'Life',
});

export const SKILLMOD = Object.freeze({
  SET: 0,
  FLAT: 1,
  PERCENT: 2,
});

export const SKILL = Object.freeze({
  BATTLE_FOCUS: 10377,
  FRENZY: 10455,
  SUNDER_EARTH: 10644,
  CHARGE: 11918,
  PRECISION_STRIKE: 12026,
  BONDBREAKER: 12034,
  WHIRLWIND_SLASH: 13282,
  TIGER_STRIKE: 13315,
  TRIPLE_SLASH: 18132,
  TERRIFYING_ROAR: 18308,
  HAMMER_TOSS: 18757,
  BEHIND_ENEMY_LINES: 23587,
  TRIPLE_SLASH_LIGHTNING: 36401,
  TRIPLE_SLASH_QUAKE: 36404,
  PRECISION_STRIKE_WAVE: 36446,
  PRECISION_STRIKE_GALE: 36447,
  TIGER_STRIKE_LIGHTNING: 36448,
  TIGER_STRIKE_LIFE: 36449,
  BEHIND_ENEMY_LINES_LIGHTNING: 39661,
  BEHIND_ENEMY_LINES_STONE: 39662,
  SUNDER_EARTH_QUAKE: 41217,
  SUNDER_EARTH_MIST: 41218,
  FRENZY_FLAME: 43188,
  FRENZY_WAVE: 43189,
  LASSITUDE: 10134,
  BUBBLE_TRAP: 10154,
  ENERVATE: 10159,
  INSIDIOUS_WHISPER: 10409,
  STILLNESS: 10665,
  PURGE: 10712,
  FOCAL_CONCUSSION: 11353,
  DAHUTAS_BREATH: 11443,
  BANSHEE_WAIL: 12001,
  EARTHEN_GRIP: 14376,
  FIENDS_KNELL: 23588,
  MIRROR_WARP: 23934,
  EARTHEN_GRIP_QUAKE: 36450,
  EARTHEN_GRIP_LIGHTNING: 36451,
  BUBBLE_TRAP_GALE: 36452,
  BUBBLE_TRAP_MIST: 36453,
  BANSHEE_WAIL_STONE: 36454,
  BANSHEE_WAIL_MIST: 36455,
  MIRROR_WARP_FLAME: 39291,
  MIRROR_WARP_STONE: 39292,
  DAHUTAS_BREATH_QUAKE: 40774,
  DAHUTAS_BREATH_MIST: 40777,
  INVINCIBILITY: 10372,
  REDOUBT: 10375,
  SHIELD_SLAM: 10399,
  MOCKING_HOWL: 10436,
  BULL_RUSH: 10501,
  EMITTING_HEALTH: 10645,
  RETRIBUTION: 10655,
  TOUGHEN: 11365,
  LASSO: 12039,
  REVITALIZING_CHEER: 12046,
  BOASTFUL_ROAR: 12048,
  IMPRISON: 14529,
  SHIELD_SLAM_GALE: 36456,
  SHIELD_SLAM_QUAKE: 36457,
  REDOUBT_GALE: 36458,
  REDOUBT_LIFE: 36459,
  IMPRISON_WAVE: 36460,
  IMPRISON_MIST: 36461,
  LASSO_GALE: 39289,
  LASSO_LIFE: 39290,
  RETRIBUTION_MIST: 40779,
  RETRIBUTION_FLAME: 40780,
  REVITALIZING_CHEER_LIFE: 42857,
  REVITALIZING_CHEER_WAVE: 42858,
  TELEPORTATION: 10152,
  VICIOUS_IMPLOSION: 10710,
  PROTECTIVE_WINGS: 10714,
  BANISHMENT: 11380,
  COURAGEOUS_ACTION: 11424,
  SHRUG_IT_OFF: 11429,
  CONVERSION_SHIELD: 11869,
  MEDITATE: 11989,
  HEALTH_LIFT: 11991,
  THWART: 16486,
  COMETS_BOON: 18222,
  BRACING_BLAST: 23589,
  THWART_MIST: 36462,
  THWART_STONE: 36463,
  CONVERSION_SHIELD_MIST: 36464,
  CONVERSION_SHIELD_FLAME: 36465,
  PROTECTIVE_WINGS_MIST: 36466,
  PROTECTIVE_WINGS_FLAME: 36467,
  TELEPORTATION_MIST: 39293,
  TELEPORTATION_LIGHTNING: 39294,
  VICIOUS_IMPLOSION_STONE: 40781,
  VICIOUS_IMPLOSION_FLAME: 40782,
  HELL_SPEAR: 10135,
  CRIPPLING_MIRE: 10201,
  SUMMON_WRAITH: 10434,
  PLAY_DEAD: 10488,
  SUMMON_CROWS: 11395,
  ABSORB_LIFEFORCE: 11441,
  PAIN_HARVEST: 11442,
  SHADOW_VORTEX: 11504,
  SHADOW_STEP: 12075,
  BONEYARD: 14760,
  DEATHS_VENGEANCE: 23591,
  CURSED_THORNS: 34171,
  HELL_SPEAR_MIST: 36586,
  HELL_SPEAR_FLAME: 36587,
  CRIPPLING_MIRE_STONE: 36620,
  CRIPPLING_MIRE_QUAKE: 36623,
  SUMMON_WRAITH_WAVE: 36626,
  SUMMON_WRAITH_MIST: 36627,
  SHADOW_STEP_WAVE: 39295,
  SHADOW_STEP_LIGHTNING: 39296,
  ABSORB_LIFEFORCE_STONE: 40785,
  ABSORB_LIFEFORCE_FLAME: 40786,
  STEADY_SHOOTING: 10694,
  HUNTERS_GUILE: 10708,
  DOUBLE_RECURVE: 11368,
  CONCUSSIVE_ARROW: 11933,
  SNARE: 12133,
  FENDING_ARROW: 12759,
  MISSILE_RAIN: 13281,
  ENDLESS_ARROWS: 14835,
  DEADEYE: 15073,
  BLAZING_ARROW: 15096,
  CHARGED_BOLT: 16210,
  SNIPE: 23592,
  CHARGED_BOLT_FLAME: 36468,
  CHARGED_BOLT_GALE: 36469,
  CONCUSSIVE_ARROW_FLAME: 36470,
  CONCUSSIVE_ARROW_MIST: 36471,
  MISSILE_RAIN_FLAME: 36472,
  MISSILE_RAIN_MIST: 36473,
  ENDLESS_ARROWS_FLAME: 39663,
  ENDLESS_ARROWS_STONE: 39666,
  SNIPE_LIGHTNING: 41219,
  SNIPE_FLAME: 41221,
  DOUBLE_RECURVE_FLAME: 42849,
  DOUBLE_RECURVE_LIFE: 42851,
  FREEZING_EARTH: 10151,
  INSULATING_LENS: 10153,
  METEOR_STRIKE: 10664,
  FREEZING_ARROW: 10667,
  ARC_LIGHTNING: 10670,
  FLAMEBOLT: 10752,
  FRIGID_TRACKS: 11314,
  SEARING_RAIN: 11939,
  CHAIN_LIGHTNING: 11967,
  MAGIC_CIRCLE: 12796,
  FLAME_BARRIER: 14774,
  GODS_WHIP: 23593,
  FLAMEBOLT_FLAME: 36474,
  FLAMEBOLT_LIGHTNING: 36475,
  CHAIN_LIGHTNING_FLAME: 36476,
  CHAIN_LIGHTNING_WAVE: 36477,
  METEOR_STRIKE_WAVE: 36478,
  METEOR_STRIKE_LIGHTNING: 36479,
  GODS_WHIP_LIGHTNING: 39669,
  GODS_WHIP_WAVE: 39674,
  FLAME_BARRIER_WAVE: 41222,
  FLAME_BARRIER_MIST: 41223,
  MAGIC_CIRCLE_QUAKE: 43068,
  MAGIC_CIRCLE_FLAME: 43185,
  STEALTH: 10082,
  LEECH: 10104,
  FREERUNNER: 10189,
  POISONED_WEAPONS: 10481,
  SHADOWSMITE: 10496,
  OVERWHELM: 10648,
  WALLOP: 12029,
  DROP_BACK: 12049,
  STALKERS_MARK: 12139,
  PIN_DOWN: 13344,
  RAPID_STRIKE: 18125,
  THROW_DAGGER: 23594,
  OVERWHELM_FLAME: 36588,
  OVERWHELM_LIGHTNING: 36589,
  DROP_BACK_MIST: 36590,
  DROP_BACK_WAVE: 36591,
  SHADOWSMITE_MIST: 36593,
  SHADOWSMITE_LIGHTNING: 36594,
  FREERUNNER_QUAKE: 39297,
  FREERUNNER_FLAME: 39298,
  POISONED_WEAPONS_FLAME: 40787,
  POISONED_WEAPONS_WAVE: 40788,
  PERFORM_QUICKSTEP: 10723,
  PERFORM_ODE_TO_RECOVERY: 10724,
  PERFORM_BLOODY_CHANTEY: 10727,
  DEADLY_REFRAIN: 11377,
  PERFORM_BULWARK_BALLAD: 11396,
  STARTLING_STRAIN: 11934,
  DISSONANCE: 11943,
  CRITICAL_DISCORD: 11973,
  HEALING_HYMN: 17413,
  BATTLE_HYMN: 23596,
  HEALING_HYMN_STONE: 36595,
  HEALING_HYMN_WAVE: 36596,
  STARTLING_STRAIN_LIFE: 36597,
  STARTLING_STRAIN_WAVE: 36598,
  SONIC_WAVE_MIST: 36628,
  SONIC_WAVE_LIFE: 36629,
  DOUBLE_TIME: 37839,
  SONIC_WAVE: 37886,
  DOUBLE_TIME_FLAME: 39299,
  DOUBLE_TIME_WAVE: 39300,
  CRITICAL_DISCORD_FLAME: 40789,
  CRITICAL_DISCORD_QUAKE: 40790,
  DISSONANCE_LIGHTNING: 43196,
  DISSONANCE_QUAKE: 43197,
  ANTITHESIS: 10534,
  REVIVE: 10546,
  RESURGENCE: 10547,
  MEND: 10720,
  MIRROR_LIGHT: 11379,
  HEALING_CIRCLE: 11948,
  SKEWER: 13286,
  FERVENT_HEALING: 14929,
  ARANZEBS_BOON: 16004,
  MANA_BARRIER: 16783,
  RENEWAL: 17412,
  HOLY_BOLT: 33345,
  ANTITHESIS_LIFE: 36630,
  ANTITHESIS_QUAKE: 36631,
  FERVENT_HEALING_LIGHTNING: 36632,
  FERVENT_HEALING_FLAME: 36635,
  LIFE_SKEWER_LIFE: 36636,
  SKEWER_FLAME: 36637,
  HOLY_BOLT_FLAME: 39675,
  HOLY_BOLT_MIST: 39676,
  HEALING_CIRCLE_WAVE: 41224,
  HEALING_CIRCLE_LIFE: 41225,
  MEND_WAVE: 43207,
  MEND_MIST: 43208,
  MEND_LIFE: 43209,
  MANA_BOLTS: 39007,
  SERPENT_GLARE: 39012,
  SOULBOUND_EDGE: 39015,
  MALICIOUS_BINDING: 39016,
  SERPENT_BITE: 39017,
  FURY: 39018,
  VOID_SURGE: 39019,
  GRASPING_VOID: 39020,
  GHASTLY_PACK: 39021,
  RING_THROW: 39022,
  SHADOW_CLOAK: 39023,
  BLADEFALL: 39024,
  MANA_BOLTS_WAVE: 39163,
  MANA_BOLTS_QUAKE: 39166,
  BLADEFALL_LIGHTNING: 39677,
  BLADEFALL_FLAME: 39678,
  SERPENT_BITE_FLAME: 40791,
  SERPENT_BITE_STONE: 40792,
  GRASPING_VOID_MIST: 41226,
  GRASPING_VOID_FLAME: 41227,
  BLADE_FLURRY: 40331,
  BLADEBLAST: 40332,
  BLINK: 40333,
  DUSK_SHROUD: 40334,
  REVERBERATE: 40335,
  RELENTLESS_ASSAULT: 40336,
  CRESCENT_SLICE: 40337,
  TWIN_SHADOW_SLASH: 40338,
  SINISTER_STRIKE: 40339,
  PRIMAL_STRIKE: 40340,
  FLEETING_FOOTSTEPS: 40341,
  ENTANGLE: 40342,
  BLADE_FLURRY_WAVE: 43211,
  BLINK_MIST: 43212,
  SINISTER_STRIKE_WAVE: 43213,

});
