export default {
  session: {
    authenticate: '/session/authenticate',
    createAccount: '/session/register',
    me: '/session/me',
  },
  service: {
    me: '/service/me',
    newsCreate: '/service/news',
    newsPage: '/service/news?page=${page}',
    newsPost: '/service/news/${postId}',
    newComment: '/service/comment',
    comment: '/service/comment/${commentId}',
    comments: '/service/comment/byPost/${postId}',
    item: '/service/item?ids=${itemIds}',
    recipeByProduct: '/service/recipe/product/${itemId}',
    recipeSearchByProduct: '/service/recipe/product',
    recipeByMaterial: '/service/recipe/material/${itemId}',
    recipeSearchByMaterial: '/service/recipe/material',
    recipeByVocation: '/service/recipe/vocation/${vocation}',
    recipe: '/service/recipe?ids=${recipeIds}',
    recipeCategories: '/service/recipe/categories',
    recipeByCategory: '/service/recipe/categories/${category}?cat1=${subCat1}&cat2=${subCat2}',
    vocations: '/service/vocations',
    searchByProduct: '/service/search/product',
    searchByMaterial: '/service/search/material',
    event: '/service/event/{eventId}',
    events: '/service/events',
    eventTypes: '/service/events/types',
    users: '/service/users?usernames=${names}',
  },
};
